<!-- Jquery JS -->
<script src="{{ url('') }}\js/jquery.min.js"></script>
<!-- Popper JS -->
<script src="{{ url('') }}\js/popper.min.js"></script>
<!-- Boostrap JS -->
<script src="{{ url('') }}\js/bootstrap.min.js"></script>
<!-- Swiper JS -->
<script src="{{ url('') }}\js/swiper.min.js"></script>
<!-- WOW JS -->
<script src="{{ url('') }}\js/wow.min.js"></script>
<!-- VenoBox JS -->
<script src="{{ url('') }}\js/venobox.min.js"></script>
<!-- App JS -->
<script src="{{ url('') }}\js/app.js"></script>